### ISSUE TITLE
Using await in a destructor

### ISSUE THREAD

**Issue by bartvanhoutte** [reactphp/async#44] opened 2022-06-02 12:37 UTC
👋 I've ran into an issue with using `await` in a destructor. The error triggered is `Fatal error: Uncaught FiberError: Cannot switch fibers in current execution context in SimpleFiber.php on line 66`.

`index.php`
```php
<?php

declare(strict_types=1);

use function React\Async\await;

require_once __DIR__ . '/vendor/autoload.php';

$foo = new class {

    public function __construct()
    {
        await(\React\Promise\Timer\sleep(1));
        print "construct\n";
    }

    public function __destruct()
    {
        await(\React\Promise\Timer\sleep(1));
        print "destruct\n";
    }

};
```
Using the `4.x` branch; the issue seems to exit with both `StreamSelectLoop` and `ExtUvLoop`.

**Comment by WyriHaximus** [comment] 2022-06-02 13:12
What happens if you wrap that in an `async()`?

**Comment by bartvanhoutte** [comment] 2022-06-02 13:35
I'm not sure on how to get the intended result with wrapping it in `async` to be honest. I know it's good practice to wrap your main entrypoint in an `async` call but if you want the exit code of the application to be dependent on the result of the async operation at some point you need to await the main fiber.

* Not wrapping the above in `async` results in the error.
* Just wrapping the above in `async` and not awaiting it results in the loop exiting immediately without anything happening.
* Wrapping the above in `async` and awaiting it results in the error, as you're basically doing the same thing as in the first list item.

**Comment by bartvanhoutte** [comment] 2022-06-03 10:15
~Worked around the problem by using a timer in combination with `async` but obviously this is slightly verbose. @WyriHaximus I've noticed you do something similar in `react/filesystem` 0.2.x branch using `PollInterface` to trick the Loop into thinking there is more work to be done.~

This pretty much sums up what I'm trying to achieve:

```php
$httpServer = new HttpServer(
  new class {


      public function __construct()
      {
          await(\React\Promise\Timer\sleep(1));
          print "construct\n";
      }

      public function __invoke(ServerRequestInterface $request, callable $next)
      {
          return $next($request);
      }

      public function __destruct()
      {
          await(\React\Promise\Timer\sleep(1));
          print "destruct\n";
      }

  },
  fn() => new Response(418),
);

$socket = new SocketServer('0.0.0.0:8080');
$httpServer->listen($socket);

Loop::addSignal(SIGTERM, $shutdown = static function () use (&$shutdown, $socket) {
    $socket->close();
    Loop::removeSignal(SIGTERM, $shutdown);
});
```

I'm trying to find a better way to `await` async operations further downstream with streaming requests, see https://github.com/reactphp/http/issues/428.

**Comment by bartvanhoutte** [comment] 2022-06-03 10:18
Workaround:

```php
public function __destruct()
{
    $timer = Loop::addPeriodicTimer((int)(PHP_INT_MAX / 1000) - 1, static fn() => 1+1);
    \React\Promise\Timer\sleep(1)->then(static fn() => Loop::cancelTimer($timer));
}
```

**Comment by WyriHaximus** [comment] 2022-06-04 09:29
Meh I thought I commented, but I suppose that never made it through:
> What are you trying to accomplish this with? Do you have an example closer to your application code?

Anyway, I wouldn't put any code that can't be fully executed immediately in the destructor as there is not a 100% guarantee it runs when you expect it to run. Since you're acting a `SIGTERM` anyway I'd dispatch an event and do the destructing there.

**Comment by clue** [comment] 2022-06-06 12:32
@bartvanhoutte Thanks for reporting, this is indeed an interesting one and I agree it's reasonable to expect this to work! :+1: 

Unfortunately, switching fiber contexts inside a destructor is not currently supported in PHP. This is a limitation of the fibers implementation in PHP 8.1, so this can be reproduced in plain PHP without using ReactPHP at all:

```php
<?php

$foo = new class
{
    public function __destruct()
    {
        $fiber = new Fiber(function () {
            Fiber::suspend(42);
        });

        var_dump($fiber->start());
    }
};

unset($foo);
```
```
$ php dtor.php 
PHP Fatal error:  Uncaught FiberError: Cannot switch fibers in current execution context in /home/me/workspace/reactphp-async/dtor.php:11
Stack trace:
#0 /home/me/workspace/reactphp-async/dtor.php(11): Fiber->start()
#1 /home/me/workspace/reactphp-async/dtor.php(15): class@anonymous->__destruct()
#2 {main}
  thrown in /home/me/workspace/reactphp-async/dtor.php on line 11
```

I agree it would be nice to see support for this in PHP and I'm not currently aware why this is not supported at the moment. Until this is supported in PHP itself, there's little we can do in ReactPHP I'm afraid. I would suggest reporting this upstream in PHP perhaps?

I hope this helps! :+1: I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:

**Closed as completed by clue** 2022-06-06 12:32 UTC
Labels: question

**Comment by bartvanhoutte** [comment] 2022-06-07 09:04
@clue perfect, I can reproduce your POC on my machine and have created a bug at https://github.com/php/php-src/issues/8723. Hope you don't mind I've copied the POC.

Thanks for the help to the both of you, I'll use a workaround until this is resolved upstream.

**Comment by WyriHaximus** [comment] 2022-06-07 09:21
@bartvanhoutte Cool, will keep an eye on that bug report
